### PR TITLE
Psanan/test refactor

### PR DESCRIPTION
**Pull request by psanan**
Apologies that this is a bit of a Frankenstein PR, but I've had it sitting around too long and would like to merge it to `dev`.

It's intended as a refactoring/formatting/cleanup step, and should still pass the self-tests.

The individual commits should be more enlightening that the full diff.

* Adds some (probably temporary) design notes to the docs
* Indents many files in the standard (PEP-8) way
* Does some preliminary integration of `Job` into `Test`
* Confines (existing) sandboxing logic to `Harness`

### CODE REVIEW

**Comment by psanan** [comment]
(Mostly addresses issue #18)

**Comment by psanan** [comment]
@dmay23  I'm going to merge this, to keep things moving along. I'll try to do a better job of not mixing formatting commits with others for future PRs, as it needlessly increases the cognitive load of reviewing!

**Comment by dmay23** [comment]
Thanks Patrick. 
I have to say, I hate PEP-8 with it's stupid 4 space tabs...

**Comment by psanan** [comment]
I have a slight preference for the 4-space tabs, because it helps (me) see alignment better, but they do waste screen space.

I advocate using PEP-8 because of the generic benefits of using a standard. Hopefully, it means less to think about. The are additional minor benefits like the fact that we can use [reindent.py](https://pypi.org/project/Reindent/) to format for us (which I used in this PR), and helper tools for Python (in my case, a plugin for vim which folds Python code) are more likely to work as intended.

**Pull request merged**
